Data preprocessing

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf 

In [2]:
tf.__version__

'2.3.0'

Loading Dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[: , 3:-1].values
Y = dataset.iloc[: , -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(Y)

[1 0 1 ... 1 1 0]


In [7]:
dataset.isnull().sum(axis=0)

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Encoding categorical data

Label encoding of Gender

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:,2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One hot encoding to Geography

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
print(Y)

[1 0 1 ... 1 1 0]


Spllitting the train and test dataset

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1234)

Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
Y_test = sc.transform(X_test)

Building the ANN

Initialiation of ANN

In [16]:
ann = tf.keras.models.Sequential()

Adding input layer and first hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding second hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='relu'))

Part 3 Training the ANN

Compiling the ANN

In [21]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

Training the ANN

In [22]:
ann.fit(X_train,Y_train, batch_size = 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 974us/step - loss: 0.5665 - accuracy: 0.7965
Epoch 2/100
250/250 [==============================] - 0s 952us/step - loss: 0.4928 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 0s 926us/step - loss: 0.4707 - accuracy: 0.8001
Epoch 4/100
250/250 [==============================] - 0s 931us/step - loss: 0.4515 - accuracy: 0.8066
Epoch 5/100
250/250 [==============================] - 0s 967us/step - loss: 0.4378 - accuracy: 0.8091
Epoch 6/100
250/250 [==============================] - 0s 944us/step - loss: 0.4306 - accuracy: 0.8117
Epoch 7/100
250/250 [==============================] - 0s 929us/step - loss: 0.4290 - accuracy: 0.8111
Epoch 8/100
250/250 [==============================] - 0s 961us/step - loss: 0.4247 - accuracy: 0.8139
Epoch 9/100
250/250 [==============================] - 0s 943us/step - loss: 0.4208 - accuracy: 0.8174
Epoch 10/100
250/250 [==============================] - 0s 894us/step - l

Part 4 Predictions of some customer in the dataset

In [23]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

[[0.03319795]]


In [24]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Predicting test set results 

In [26]:
import numpy as np

Y_pred = np.asarray(Y_pred).astype(np.float32)

NameError: ignored

In [27]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

ValueError: ignored

 Making confusion Matrix

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

##Out was 
#[[1520  75]]
#[[202 203]]

##Acc 0.8615


NameError: ignored